version: "3.7"

services:
  web:
    image: nginx:1.20.2
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - www
    extra_hosts:
        host.docker.internal: host-gateway
    working_dir: /var/www
networks:
  www:
