version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - www
    extra_hosts:
        host.docker.internal: host-gateway
    working_dir: /var/www
    links:
      - mysql
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8088:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: always
    depends_on:
        - mysql
    networks:
        - www
  mysql:
    build:
      dockerfile: ./mysql/dockerfile
    image: mysql:8
    container_name: mysql
    environment:
      - DB_DSN="mysql:dbname=database;host=mysql"
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - www

networks:
  www:
